version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-github
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 20
    groups:
      all-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      navikt-aksel-minor-patch:
        patterns:
          - '@navikt/*'
        exclude-patterns:
          - '@navikt/nav-dekoratoren-moduler'
        update-types:
          - 'minor'
          - 'patch'
      navikt-aksel-major:
        patterns:
          - '@navikt/*'
        exclude-patterns:
          - '@navikt/nav-dekoratoren-moduler'
        update-types:
          - 'major'
      react-and-next:
        patterns:
          - 'react*'
          - 'next*'
        update-types:
          - 'major'
      eslint-typescript-cypress-minor-patch:
        patterns:
          - '*eslint*'
          - '*typescript*'
          - '*cypress*'
        update-types:
          - 'minor'
          - 'patch'
      eslint-typescript-cypress-major:
        patterns:
          - '*eslint*'
          - '*typescript*'
          - '*cypress*'
        update-types:
          - 'major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
