apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: send-inn-frontend
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '50M'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
  image: '{{ image }}'
  port: 3100
  liveness:
    path: /sendinn/api/isAlive
    initialDelay: 20
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sendinn/api/isReady
    initialDelay: 20
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /sendinn/api/internal/prometheus
  resources:
    limits:
      memory: 786Mi
    requests:
      memory: 512Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: innsending-api
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
    - 'https://www.intern.dev.nav.no/sendinn'
  env:
    - name: APP_VERSION
      value: {{ app_version }}
    - name: INNSENDING_API_AUDIENCE
      value: 'dev-gcp:team-soknad:innsending-api'
    - name: REMOTE_API_URL
      value: 'http://innsending-api'
    - name: LOG_LINK
      value: https://logs.adeo.no/app/discover#/view/b80c8870-6da3-11ee-b740-7d0ae42f37a4
