apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: send-inn-frontend
    namespace: team-soknad
    labels:
        team: team-soknad
    annotations:
        nais.io/security-does-not-matter: "true"
spec:
    image: "{{ image }}"
    port: 3000
    liveness:
        path: /api/isAlive
        initialDelay: 20
    readiness:
        path: /api/isReady
        initialDelay: 20
    replicas:
        min: 1
        max: 2
        cpuThresholdPercentage: 50
    prometheus:
        enabled: true
        path: /internal/metrics
    resources:
        limits:
            memory: 786Mi
        requests:
            memory: 512Mi
    ingresses:
        - "https://send-inn-frontend.dev.nav.no"
    env:
        - name: APP_VERSION
          value: {{ app_version }}
