apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: send-inn-frontend
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nais.io/security-does-not-matter: 'true'
spec:
  image: "{{ image }}"
  port: 80
  liveness:
    path: isAlive
    initialDelay: 20
  readiness:
    path: isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: soknadsadmins/internal/metrics
  resources:
    limits:
      memory: 786Mi
    requests:
      memory: 512Mi
  ingresses:
    - "https://send-inn-frontend.dev.nav.no"
  vault:
    enabled: true
  webproxy: true
  env:
    - name: APPRES_CMS_URL
      value: https://appres-default.nav.no
    - name: APP_VERSION
      value: {{ app_version }}
