apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: send-inn-frontend
    namespace: team-soknad
    labels:
        team: team-soknad
spec:
    image: '{{ image }}'
    port: 80
    liveness:
        path: isAlive
        initialDelay: 120
        timeout: 10
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: isReady
        initialDelay: 120
        timeout: 10
    replicas:
        min: 2
        max: 4
        cpuThresholdPercentage: 50
    prometheus:
        enabled: true
        path: /internal/metrics
    resources:
        limits:
            memory: 786Mi
        requests:
            memory: 512Mi
    ingresses:
        - 'https://send-inn-frontend.nais.oera.no'
    vault:
        enabled: true
    env:
        - name: APP_VERSION
          value: { { app_version } }
