export const FIL_STATUS = {
    OPPRETTET: 'OPPRETTET',
    STARTER_OPPLASTNING: 'STARTER_OPPLASTNING',
    LASTER_OPP: 'LASTER_OPP',
    OPPLASTET: 'OPPLASTET',
    AVBRUTT: 'AVBRUTT',
    SLETTER: 'SLETTER',
    FEIL: 'FEIL',
    TIDLIGERE_LASTET_OPP: 'TIDLIGERE_LASTET_OPP',
} as const;
