import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        // <div>
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Dev</h1>

                {/* TODO fix trailing comma buggen ... http://localhost:3000/dokumentinnsending/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=false&vedleggsIder=C1,W1,G2," <- ,*/}
                <div>
                    <Link
                        href={
                            '/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=false&vedleggsIder=C1,W1,G2'
                        }
                        passHref
                    >
                        <a target="_blank" rel="noopener noreferrer">
                            Dokumentinnsending - Opprett søknad
                        </a>
                    </Link>
                </div>
                <div>
                    <Link
                        href={
                            '/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=true&vedleggsIder=C1,W1,G2'
                        }
                        passHref
                    >
                        <a target="_blank" rel="noopener noreferrer">
                            Dokumentinnsending - Opprett ettersending
                        </a>
                    </Link>
                </div>
                <div>
                    <Link
                        href={
                            '/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=true&vedleggsIder=C1,W1,G2'
                        }
                        passHref
                    >
                        <a target="_blank" rel="noopener noreferrer">
                            Dokumentinnsending - Opprett ettersending
                        </a>
                    </Link>
                </div>

                <div>
                    <Link
                        href={
                            '/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=EN&erEttersendelse=false&vedleggsIder=C1,W1,G2'
                        }
                        passHref
                    >
                        <a target="_blank" rel="noopener noreferrer">
                            Dokumentinnsending - Opprett søknad,
                            Engelsk
                        </a>
                    </Link>
                </div>

                <div>
                    <Link
                        href={
                            '/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NN&erEttersendelse=false&vedleggsIder=C1,W1,G2'
                        }
                        passHref
                    >
                        <a target="_blank" rel="noopener noreferrer">
                            Dokumentinnsending - Opprett søknad,
                            Nynorsk
                        </a>
                    </Link>
                </div>

                <div>
                    <Link
                        href={
                            '/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=false'
                        }
                        passHref
                    >
                        <a target="_blank" rel="noopener noreferrer">
                            Dokumentinnsending - Opprett søknad, uten
                            vedlegg
                        </a>
                    </Link>
                </div>
            </main>

            <footer></footer>
        </div>
    );
};

export default Home;
