import type { NextPage } from 'next';
import Head from 'next/head';
// import styles from '../styles/Home.module.css';
import Link from 'next/link';

import '../i18n';

const Home: NextPage = () => {
    return (
        // <div>
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Dev</h1>

                {/* TODO fix trailing comma buggen ... http://localhost:3000/dokumentinnsending/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=false&vedleggsIder=C1,W1,G2," <- ,*/}
                <div>
                    <a
                        href={
                            '/dev/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=false&vedleggsIder=C1,W1,G2'
                        }
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Dokumentinnsending - Opprett søknad
                    </a>
                </div>
                <div>
                    <a
                        href={
                            '/dev/opprettSoknadResource?skjemanummer=NAV%2054-00.04&sprak=NO_NB&erEttersendelse=true&vedleggsIder=C1,W1,G2'
                        }
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Dokumentinnsending - Opprett ettersending
                    </a>
                </div>
            </main>

            <footer></footer>
        </div>
    );
};

export default Home;
