name: Build and push Docker container
on:
  workflow_call:
    outputs:
      image:
        description: 'The docker image'
        value: ${{ jobs.build-and-push.outputs.image }}
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@navikt'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        run: cp environments/${{ inputs.environment }}.env .env
      - name: Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-soknad
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ inputs.environment }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
