name: Build, push, and deploy
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/**.md'
env:
    IMAGE: ghcr.io/${{ github.repository }}/send-inn-frontend:prod_${{ github.sha }}
    CI: true
    TZ: Europe/Oslo

jobs:
    build-and-test:
      name: Test frontend
      uses: ./.github/workflows/test.yml

    build-and-push:
        name: Build and push Docker container
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set environment variables (prod)
              run: cp environments/prod.env .env
            - name: Build and push Docker container
              uses: ./.github/workflows/build-push.yml

    deploy-prod:
        name: Deploy to prod
        needs: [build-and-test, build-and-push]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  DRY_RUN: false
                  PRINT_PAYLOAD: true
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/nais.yml
                  VAR: app_version=${{ github.sha }}
