name: Build, push, and deploy (preprod-alt)
on: workflow_call

jobs:
    build-and-test:
      name: Test frontend
      uses: ./.github/workflows/test.yml

    build-and-push:
      name: Build and push Docker container for preprod
      uses: ./.github/workflows/build-push.yml
      with: 
        environment: preprod-alt
      secrets: inherit

    deploy-preprod:
        name: Deploy to preprod-alt
        needs: [build-and-test, build-and-push]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  DRY_RUN: false
                  PRINT_PAYLOAD: true
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/nais-preprod-alt.yml
                  VAR: app_version=${{ github.sha }},image=${{ needs.build-and-push.outputs.image }}
